
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-04
owner: ucsb-cs156-s25
repo_name: team02-s25-04
pull_requests: [{"author":{"id":"U_kgDOBthD0Q","is_bot":false,"login":"ethansolomon49","name":""},"headRefName":"Ethan-UCSBDiningCommonsMenuItem-fixture","number":62,"title":"Ethan ucsb dining commons menu item fixture","url":"https://github.com/ucsb-cs156-s25/team02-s25-04/pull/62"},{"author":{"id":"U_kgDOBthD0Q","is_bot":false,"login":"ethansolomon49","name":""},"headRefName":"Ethan-UCSBDiningCommonsMenuItem-backend","number":61,"title":"copied backend for ucsb dining commons menu items from team01","url":"https://github.com/ucsb-cs156-s25/team02-s25-04/pull/61"}]
