
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-04
owner: ucsb-cs156-s25
repo_name: team02-s25-04
pull_requests: [{"author":{"id":"U_kgDOCvDiEw","is_bot":false,"login":"ZFahim10","name":""},"headRefName":"Fahim-HelpRequest-E2Etests","number":123,"title":"Fahim help request e2e tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-04/pull/123"},{"author":{"id":"U_kgDOCvDiEw","is_bot":false,"login":"ZFahim10","name":""},"headRefName":"Fahim-HelpRequest-IntegrationTests","number":122,"title":"Fahim help request integration tests","url":"https://github.com/ucsb-cs156-s25/team02-s25-04/pull/122"},{"author":{"id":"U_kgDOCt_6qQ","is_bot":false,"login":"Renbo2004","name":""},"headRefName":"Renbo-Articles-End-2-End-Test","number":118,"title":"pc - articles end 2 end test","url":"https://github.com/ucsb-cs156-s25/team02-s25-04/pull/118"}]
