
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-04
owner: ucsb-cs156-s25
repo_name: team02-s25-04
pull_requests: [{"author":{"id":"MDQ6VXNlcjQ5ODgzNjQy","is_bot":false,"login":"jeremiahwong704","name":"Jeremiah Wong"},"headRefName":"jerry-team03","number":88,"title":"Jerry team03","url":"https://github.com/ucsb-cs156-s25/team02-s25-04/pull/88"},{"author":{"id":"U_kgDOCMR7LA","is_bot":false,"login":"Asuasuasu1","name":"Montgomery Forde"},"headRefName":"Montgomery-commit-fixtures","number":87,"title":"mf - add javascript fixtures for ucsborganization table ","url":"https://github.com/ucsb-cs156-s25/team02-s25-04/pull/87"},{"author":{"id":"U_kgDOCMR7LA","is_bot":false,"login":"Asuasuasu1","name":"Montgomery Forde"},"headRefName":"Montgomery-CopyCrudOperations","number":86,"title":"copied backend CRUD operations from team01 for UCSBOrganization table","url":"https://github.com/ucsb-cs156-s25/team02-s25-04/pull/86"},{"author":{"id":"U_kgDOBthD0Q","is_bot":false,"login":"ethansolomon49","name":""},"headRefName":"Ethan-End2EndTest","number":84,"title":"Ethan End 2 End Test","url":"https://github.com/ucsb-cs156-s25/team02-s25-04/pull/84"}]
