
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-04
owner: ucsb-cs156-s25
repo_name: team02-s25-04
pull_requests: [{"author":{"id":"U_kgDOBqwIXg","is_bot":false,"login":"j1yl","name":"Joe Lee"},"headRefName":"Joe-CopyPlaceholders","number":92,"title":"Copy Placeholders for RecommendationRequest pages","url":"https://github.com/ucsb-cs156-s25/team02-s25-04/pull/92"},{"author":{"id":"U_kgDOBqwIXg","is_bot":false,"login":"j1yl","name":"Joe Lee"},"headRefName":"Joe-Fixtures","number":91,"title":"Add fixtures for RecommendationRequest","url":"https://github.com/ucsb-cs156-s25/team02-s25-04/pull/91"},{"author":{"id":"U_kgDOBqwIXg","is_bot":false,"login":"j1yl","name":"Joe Lee"},"headRefName":"Joe-Copyfiles","number":90,"title":"Copy files for Backend CRUD API RecommendationRequest from team02","url":"https://github.com/ucsb-cs156-s25/team02-s25-04/pull/90"},{"author":{"id":"U_kgDOCMR7LA","is_bot":false,"login":"Asuasuasu1","name":"Montgomery Forde"},"headRefName":"Montgomery-FormComponent-UCSBOrganizations","number":89,"title":"Montgomery - Add form for UCSBOrganizations","url":"https://github.com/ucsb-cs156-s25/team02-s25-04/pull/89"},{"author":{"id":"U_kgDOCMR7LA","is_bot":false,"login":"Asuasuasu1","name":"Montgomery Forde"},"headRefName":"Montgomery-commit-fixtures","number":87,"title":"mf - add javascript fixtures for ucsborganization table ","url":"https://github.com/ucsb-cs156-s25/team02-s25-04/pull/87"},{"author":{"id":"U_kgDOCMR7LA","is_bot":false,"login":"Asuasuasu1","name":"Montgomery Forde"},"headRefName":"Montgomery-CopyCrudOperations","number":86,"title":"copied backend CRUD operations from team01 for UCSBOrganization table","url":"https://github.com/ucsb-cs156-s25/team02-s25-04/pull/86"}]
