
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s25/team02-s25-04
owner: ucsb-cs156-s25
repo_name: team02-s25-04
pull_requests: [{"author":{"id":"U_kgDOCt_6qQ","is_bot":false,"login":"Renbo2004","name":""},"headRefName":"Renbo-Articles-Edit-Page","number":110,"title":"Renbo articles edit page","url":"https://github.com/ucsb-cs156-s25/team02-s25-04/pull/110"},{"author":{"id":"U_kgDOCt_6qQ","is_bot":false,"login":"Renbo2004","name":""},"headRefName":"Renbo-Articles-Index-Page","number":109,"title":"pc - add articles index page","url":"https://github.com/ucsb-cs156-s25/team02-s25-04/pull/109"},{"author":{"id":"U_kgDOBqwIXg","is_bot":false,"login":"j1yl","name":"Joe Lee"},"headRefName":"Joe-RecommendationRequestEditPage","number":108,"title":"Add recommendation request edit page","url":"https://github.com/ucsb-cs156-s25/team02-s25-04/pull/108"},{"author":{"id":"U_kgDOCvDiEw","is_bot":false,"login":"ZFahim10","name":""},"headRefName":"Fahim-HelpRequest-Pages","number":107,"title":"fz - updated frontend to include pages for HelpRequests","url":"https://github.com/ucsb-cs156-s25/team02-s25-04/pull/107"},{"author":{"id":"U_kgDOBqwIXg","is_bot":false,"login":"j1yl","name":"Joe Lee"},"headRefName":"Joe-RecommendationRequestIndexPage","number":106,"title":"Add RecommendationRequest Index page","url":"https://github.com/ucsb-cs156-s25/team02-s25-04/pull/106"},{"author":{"id":"U_kgDOCvDiEw","is_bot":false,"login":"ZFahim10","name":""},"headRefName":"Fahim-HelpRequest-Table","number":105,"title":"Fahim help request table","url":"https://github.com/ucsb-cs156-s25/team02-s25-04/pull/105"},{"author":{"id":"U_kgDOCt_6qQ","is_bot":false,"login":"Renbo2004","name":""},"headRefName":"Renbo-Articles-Create-Page","number":104,"title":"pc - add articles create page","url":"https://github.com/ucsb-cs156-s25/team02-s25-04/pull/104"},{"author":{"id":"U_kgDOBqwIXg","is_bot":false,"login":"j1yl","name":"Joe Lee"},"headRefName":"Joe-RecommendationRequestCreatePage","number":103,"title":"Add recommendation request create page","url":"https://github.com/ucsb-cs156-s25/team02-s25-04/pull/103"},{"author":{"id":"U_kgDOCt_6qQ","is_bot":false,"login":"Renbo2004","name":""},"headRefName":"Renbo-Articles-Placeholders-Page","number":102,"title":"pc - add articles placeholders pages","url":"https://github.com/ucsb-cs156-s25/team02-s25-04/pull/102"},{"author":{"id":"U_kgDOBqwIXg","is_bot":false,"login":"j1yl","name":"Joe Lee"},"headRefName":"Joe-RecommendationRequestTable","number":100,"title":"Add RecommendationRequest table","url":"https://github.com/ucsb-cs156-s25/team02-s25-04/pull/100"}]
